mod authority_attr;
mod bound_attr;
mod config;
mod instruction_attr;
mod invariant_attr;
mod snapshot;
mod tx_anchor_codegen;
mod types;
mod program_attr;

use std::collections::HashMap;

use proc_macro::TokenStream;
use proc_macro2::TokenStream as TokenStream2;
use quote::{quote, format_ident};
use syn::{
    parse_macro_input, Item, ItemFn, ItemMod, Visibility,
};

/// Extract public function items from a module's content.
fn extract_pub_fns(module: &ItemMod) -> Vec<&ItemFn> {
    let mut fns = Vec::new();
    if let Some((_, items)) = &module.content {
        for item in items {
            if let Item::Fn(f) = item {
                if matches!(f.vis, Visibility::Public(_)) {
                    fns.push(f);
                }
            }
        }
    }
    fns
}

/// Program-level attribute that generates the sandbox entrypoint wrapper.
/// Replaces Anchor's `#[program]` when the sandbox feature is enabled.
///
/// This macro generates:
/// 1. The Anchor `#[program]` expansion (entrypoint, dispatch, ID module)
/// 2. A sandbox wrapper entrypoint that intercepts before/after dispatch
///
/// Usage:
/// ```ignore
/// #[cfg_attr(feature = "sandbox", sandbox_program(config = "sandbox.toml"))]
/// #[cfg_attr(not(feature = "sandbox"), program)]
/// pub mod my_program {
///     use super::*;
///     pub fn initialize(ctx: Context<Initialize>) -> Result<()> { ... }
/// }
/// ```
#[proc_macro_attribute]
pub fn sandbox_program(attr: TokenStream, item: TokenStream) -> TokenStream {
    let module = parse_macro_input!(item as ItemMod);

    // Parse optional config attribute: sandbox_program(config = "sandbox.toml")
    let config_path = parse_config_path(attr);

    // Load and parse config from sandbox.toml
    let sandbox_config = if let Some(ref path) = config_path {
        match config::load_config(path) {
            Ok(c) => Some(c),
            Err(e) => {
                let msg = format!("Failed to load sandbox config: {}", e);
                return quote! { compile_error!(#msg); }.into();
            }
        }
    } else {
        None
    };

    // Convert parsed config into the program_attr config types
    let program_config = build_program_config(&sandbox_config);

    // Extract module name for ID generation
    let mod_name = &module.ident;

    // Extract all public functions (instruction handlers)
    let pub_fns = extract_pub_fns(&module);

    // Parse instruction-level attributes from each pub fn
    let instruction_metas: Vec<_> = pub_fns
        .iter()
        .filter_map(|f| instruction_attr::parse_instruction_attrs(f).ok())
        .collect();

    // Generate discriminator match arms for dispatch
    let dispatch_arms = program_attr::generate_dispatch_arms(&pub_fns, mod_name);

    // Generate the Anchor-compatible __instruction module with handler wrappers
    let instruction_mod = program_attr::generate_instruction_module(&pub_fns, mod_name);

    // Extract accounts config for field resolution
    let accounts_config = sandbox_config.as_ref().and_then(|c| c.accounts.clone());

    // Generate per-instruction sandbox wrappers with pre/post checks
    let instruction_wrappers = generate_instruction_wrappers(
        &instruction_metas,
        mod_name,
        &program_config,
        &accounts_config,
    );

    // Build the program ID declaration (Anchor convention)
    let id_mod = program_attr::generate_id_module(mod_name);

    // The inner module is preserved as-is so all user types/fns remain accessible
    let preserved_module = &module;

    // Collect tx_cumulative_decrease field paths across all instructions (for step [5] anchor)
    let tx_anchor_fields: Vec<String> = {
        let mut fields = Vec::new();
        for meta in &instruction_metas {
            for inv in &meta.invariants {
                if let instruction_attr::InvariantType::TxCumulativeDecrease { field, .. } = inv {
                    if !fields.contains(field) {
                        fields.push(field.clone());
                    }
                }
            }
        }
        fields
    };

    // Generate the sandbox entrypoint - this IS the Solana entrypoint.
    let entrypoint = program_attr::generate_sandbox_entrypoint(
        mod_name, &dispatch_arms, &program_config, &pub_fns, &tx_anchor_fields,
    );

    let output = quote! {
        // ═══════════════════════════════════════════════════════════════════
        // Generated by #[sandbox_program] - PERK Sandbox v0.1
        // This replaces Anchor's #[program] and adds sandbox wrapping.
        // ═══════════════════════════════════════════════════════════════════

        // ── Preserve the original module (user's business logic) ──
        #preserved_module

        // ── Anchor-compatible instruction dispatch wrappers ──
        #instruction_mod

        // ── Per-instruction sandbox wrappers (pre/post checks) ──
        #instruction_wrappers

        // ── Program ID module (Anchor convention) ──
        #id_mod

        // ── Sandbox entrypoint (THE Solana entrypoint - no bypass) ──
        #entrypoint
    };

    output.into()
}

/// Generate per-instruction sandbox wrappers with pre/post checks.
///
/// Each wrapper includes authority checks, bound checks, snapshot placeholders,
/// calls the Anchor-deserialized handler, then runs invariant post-checks.
fn generate_instruction_wrappers(
    metas: &[instruction_attr::InstructionMeta],
    mod_name: &syn::Ident,
    config: &program_attr::SandboxConfig,
    accounts_config: &Option<HashMap<String, config::AccountConfig>>,
) -> proc_macro2::TokenStream {
    let wrappers: Vec<proc_macro2::TokenStream> = metas
        .iter()
        .map(|meta| {
            generate_single_wrapper(meta, mod_name, config, accounts_config)
        })
        .collect();

    quote! {
        /// Per-instruction sandbox wrappers with pre/post checks.
        #[doc(hidden)]
        mod __sandbox_wrappers {
            use super::*;

            #(#wrappers)*
        }
    }
}

/// Generate a single instruction wrapper with authority, bound, and invariant checks.
fn generate_single_wrapper(
    meta: &instruction_attr::InstructionMeta,
    mod_name: &syn::Ident,
    config: &program_attr::SandboxConfig,
    accounts_config: &Option<HashMap<String, config::AccountConfig>>,
) -> proc_macro2::TokenStream {
    let fn_name = syn::Ident::new(&meta.name, proc_macro2::Span::call_site());
    let fn_name_str = &meta.name;

    // ── SNAPSHOT FIELD RESOLUTION ──
    // Collect field paths referenced by this instruction's invariants,
    // resolve them to FieldRefs via accounts config, generate before/after reads.
    let field_paths = collect_field_paths_from_instruction_meta(meta);
    // Circuit breaker tracked field reads are done in the main entrypoint
    // (step [6b] before + step [9] after), not via per-instruction snapshots.
    let (before_snapshot_block, after_snapshot_block) = if let Some(accts) = accounts_config {
        match snapshot::resolve_field_refs(&field_paths, accts) {
            Ok(field_refs) if !field_refs.is_empty() => {
                let before = snapshot::generate_before_snapshots(&field_refs);
                let after = snapshot::generate_after_reads(&field_refs);
                (before, after)
            }
            Ok(_) => (quote! {}, quote! {}),  // no fields to snapshot
            Err(e) => {
                // Field resolution failed - emit compile error so developer sees the issue
                let err_msg = format!(
                    "Snapshot field resolution failed for instruction '{}': {}",
                    meta.name, e
                );
                let err_block = quote! { compile_error!(#err_msg); };
                (err_block.clone(), err_block)
            }
        }
    } else {
        (quote! {}, quote! {})
    };

    // Authority pre-checks
    let authority_checks: Vec<proc_macro2::TokenStream> = meta
        .authorities
        .iter()
        .map(|req| {
            match req {
                types::AuthorityRequirement::OwnerOf(path) => {
                    generate_owner_of_check(path, accounts_config, fn_name_str)
                }
                _ => {
                    authority_attr::generate_authority_check(req, &Some(config.keys.clone()))
                }
            }
        })
        .collect();

    let authority_block = if authority_checks.is_empty() {
        quote! {}
    } else {
        quote! {
            // ── [4a] Authority pre-checks ──
            #(#authority_checks)*
        }
    };

    // Bound pre-checks (using bound_attr codegen for typed constraints)
    let bound_checks: Vec<proc_macro2::TokenStream> = meta
        .bounds
        .iter()
        .map(|b| {
            let lhs_ident = syn::Ident::new(&b.lhs, proc_macro2::Span::call_site());
            let rhs_tokens: proc_macro2::TokenStream = b.rhs.parse().unwrap_or_else(|_| {
                let rhs_ident = syn::Ident::new(&b.rhs, proc_macro2::Span::call_site());
                quote! { #rhs_ident }
            });
            let bound_desc = format!("{} {} {}", b.lhs, b.op.as_str(), b.rhs);
            let check = match b.op {
                instruction_attr::BoundOp::Gte => quote! { #lhs_ident >= #rhs_tokens },
                instruction_attr::BoundOp::Lte => quote! { #lhs_ident <= #rhs_tokens },
                instruction_attr::BoundOp::Gt => quote! { #lhs_ident > #rhs_tokens },
                instruction_attr::BoundOp::Lt => quote! { #lhs_ident < #rhs_tokens },
                instruction_attr::BoundOp::Eq => quote! { #lhs_ident == #rhs_tokens },
                instruction_attr::BoundOp::Ne => quote! { #lhs_ident != #rhs_tokens },
            };
            quote! {
                if !(#check) {
                    anchor_lang::prelude::msg!(
                        "PERK_SANDBOX:type=bound_violation,constraint={}",
                        #bound_desc
                    );
                    return Err(anchor_lang::solana_program::program_error::ProgramError::Custom(6040u32));
                }
            }
        })
        .collect();

    // Arg deserialization for bound checks (only if we have bounds)
    let arg_deser_block = if !meta.bounds.is_empty() && !meta.args.is_empty() {
        let arg_desers: Vec<proc_macro2::TokenStream> = meta.args.iter().map(|(name, ty)| {
            let arg_ident = syn::Ident::new(name, proc_macro2::Span::call_site());
            let arg_type: proc_macro2::TokenStream = ty.parse().unwrap_or_else(|_| quote! { u64 });
            quote! {
                let #arg_ident: #arg_type = anchor_lang::AnchorDeserialize::deserialize(
                    &mut __sb_bound_cursor
                ).map_err(|_| anchor_lang::solana_program::program_error::ProgramError::Custom(6040u32))?;
            }
        }).collect();
        quote! {
            // Deserialize instruction args for bound pre-checks
            let mut __sb_bound_cursor: &[u8] = &ix_data[8..];
            #(#arg_desers)*
        }
    } else {
        quote! {}
    };

    let bound_block = if bound_checks.is_empty() {
        quote! {}
    } else {
        quote! {
            // ── [4d] Bound pre-checks ──
            #(#bound_checks)*
        }
    };

    // Invariant post-checks (skip during bypass except tx_cumulative_decrease)
    let normal_invariant_checks: Vec<proc_macro2::TokenStream> = meta
        .invariants
        .iter()
        .filter(|inv| !matches!(inv, instruction_attr::InvariantType::TxCumulativeDecrease { .. }))
        .filter_map(|inv| {
            // Convert parse-level InvariantType → canonical InvariantType → codegen
            let canonical = resolve_invariant_type(inv)?;
            Some(invariant_attr::generate_invariant_check(&canonical, &meta.name))
        })
        .collect();

    let invariant_block = if normal_invariant_checks.is_empty() {
        quote! {}
    } else {
        quote! {
            // ── [8a] Instruction-level invariant post-checks ──
            if !__sandbox_emergency_bypass {
                #(#normal_invariant_checks)*
            }
        }
    };

    // tx_cumulative_decrease checks (ALWAYS run, even during bypass)
    let tx_decrease_checks: Vec<proc_macro2::TokenStream> = meta
        .invariants
        .iter()
        .filter_map(|inv| {
            if let instruction_attr::InvariantType::TxCumulativeDecrease { field, max_pct } = inv {
                let parts: Vec<&str> = field.splitn(2, '.').collect();
                if parts.len() == 2 {
                    let anchor_field = tx_anchor_codegen::TxAnchorField {
                        account_name: parts[0].to_string(),
                        field_path: parts[1].to_string(),
                        field_type: "u64".to_string(),
                    };
                    Some(tx_anchor_codegen::generate_tx_cumulative_decrease_check(
                        &anchor_field,
                        *max_pct,
                    ))
                } else {
                    None
                }
            } else {
                None
            }
        })
        .collect();

    // Build the anchor field write expressions for first-invocation snapshot
    let tx_anchor_write_exprs: Vec<proc_macro2::TokenStream> = meta
        .invariants
        .iter()
        .filter_map(|inv| {
            if let instruction_attr::InvariantType::TxCumulativeDecrease { field, .. } = inv {
                let parts: Vec<&str> = field.splitn(2, '.').collect();
                if parts.len() == 2 {
                    let account_ident = syn::Ident::new(parts[0], proc_macro2::Span::call_site());
                    let field_ident = syn::Ident::new(parts[1], proc_macro2::Span::call_site());
                    Some(quote! {
                        (
                            *ctx.accounts.#account_ident.to_account_info().key,
                            ctx.accounts.#account_ident.#field_ident as u64,
                        )
                    })
                } else {
                    None
                }
            } else {
                None
            }
        })
        .collect();

    let tx_decrease_block = if tx_decrease_checks.is_empty() {
        quote! {}
    } else {
        quote! {
            // ── [8c] tx_cumulative_decrease checks (ALWAYS run, even during bypass) ──

            // Resolve anchor fields: on first invocation snapshot + write,
            // on subsequent use the stored values from the main entrypoint.
            let __sandbox_tx_anchor_fields = if __sandbox_tx_anchor_fields.is_empty() {
                // First invocation: snapshot field values from Anchor context
                let __anchor_snapshot: Vec<(
                    anchor_lang::solana_program::pubkey::Pubkey, u64
                )> = vec![
                    #(#tx_anchor_write_exprs),*
                ];
                // Write to PDA (fail-closed: propagate borrow errors)
                {
                    let mut pda_data = __sandbox_pda_info.try_borrow_mut_data()
                        .map_err(|_| anchor_lang::solana_program::program_error::ProgramError::Custom(
                            perk_sandbox_runtime::error::SandboxError::SnapshotFailed as u32
                        ))?;
                    let __tx_off = u16::from_le_bytes([
                        pda_data[perk_sandbox_runtime::state::OFF_TX_ANCHOR],
                        pda_data[perk_sandbox_runtime::state::OFF_TX_ANCHOR + 1],
                    ]) as usize;
                    if __tx_off > 0 {
                        perk_sandbox_runtime::tx_anchor::write_anchor_fields_only(
                            &mut pda_data[__tx_off..],
                            &__anchor_snapshot,
                        );
                    }
                    drop(pda_data);
                }
                __anchor_snapshot
            } else {
                // Subsequent invocation: use stored values from main entrypoint
                __sandbox_tx_anchor_fields
            };

            #(#tx_decrease_checks)*
        }
    };

    // Determine circuit breaker category
    let category_variant = match &meta.circuit_breaker_category {
        Some(cat) => {
            let resolved = instruction_attr::resolve_category(cat, &Some(cat.clone()), &HashMap::new());
            let variant = syn::Ident::new(resolved.variant_name(), proc_macro2::Span::call_site());
            quote! { perk_sandbox_runtime::circuit_breaker::InstructionCategory::#variant }
        }
        None => {
            quote! { perk_sandbox_runtime::circuit_breaker::InstructionCategory::Default }
        }
    };

    let is_recovery = meta.is_recovery;

    quote! {
        /// Generated sandbox wrapper for instruction `#fn_name_str`.
        #[allow(unused_variables)]
        pub fn #fn_name<'info>(
            program_id: &anchor_lang::solana_program::pubkey::Pubkey,
            accounts: &'info [anchor_lang::solana_program::account_info::AccountInfo<'info>],
            ix_data: &[u8],
            __sandbox_emergency_bypass: bool,
        ) -> std::result::Result<
            perk_sandbox_runtime::circuit_breaker::InstructionCategory,
            anchor_lang::solana_program::program_error::ProgramError,
        > {
            let __sandbox_is_recovery: bool = #is_recovery;

            // ════════════════════════════════════════════════════════
            // PRE-CHECKS (always run, including re-entrant + bypass)
            // ════════════════════════════════════════════════════════

            #authority_block

            #arg_deser_block
            #bound_block

            // ════════════════════════════════════════════════════════
            // SNAPSHOT [6] - instruction-level before-snapshots
            // ════════════════════════════════════════════════════════
            #before_snapshot_block

            // ════════════════════════════════════════════════════════
            // BUSINESS LOGIC [7] - dispatch through __sandbox_instruction
            // ════════════════════════════════════════════════════════
            let __dispatch_result = __sandbox_instruction::#fn_name(
                program_id, accounts, &ix_data[8..]
            );

            if let Err(e) = __dispatch_result {
                anchor_lang::prelude::msg!(
                    concat!("PERK_SANDBOX:type=dispatch_error,ix=", #fn_name_str)
                );
                return Err(e.into());
            }

            // ════════════════════════════════════════════════════════
            // SNAPSHOT [6b] - instruction-level after-reads
            // ════════════════════════════════════════════════════════
            #after_snapshot_block

            // ════════════════════════════════════════════════════════
            // POST-CHECKS [8]
            // ════════════════════════════════════════════════════════

            #invariant_block

            #tx_decrease_block

            Ok(#category_variant)
        }
    }
}

/// Generate an OwnerOf authority check.
///
/// `path` is like "ctx.accounts.position" or "ctx.accounts.position.owner".
/// This reads the authority/owner pubkey from the account at a known byte offset
/// (from sandbox.toml config) and compares it to the transaction signer.
///
/// Strategy: Use the snapshot system to read the pubkey field, then compare.
fn generate_owner_of_check(
    path: &str,
    accounts_config: &Option<HashMap<String, config::AccountConfig>>,
    fn_name_str: &str,
) -> proc_macro2::TokenStream {
    // Strip "ctx.accounts." prefix if present
    let stripped = path
        .strip_prefix("ctx.accounts.")
        .unwrap_or(path);

    // Split into account name and optional field name
    // "position" → account="position", field="authority" (default)
    // "position.owner" → account="position", field="owner"
    let (account_name, field_name) = if let Some(dot_pos) = stripped.find('.') {
        (&stripped[..dot_pos], &stripped[dot_pos + 1..])
    } else {
        (stripped, "authority") // default field name
    };

    // Try to resolve the field from accounts config
    let field_path = format!("{}.{}", account_name, field_name);

    if let Some(accts) = accounts_config {
        match snapshot::resolve_field_ref(&field_path, accts) {
            Ok(field_ref) => {
                // Verify it's a Pubkey field
                if field_ref.field_type != snapshot::FieldType::Pubkey {
                    let err_msg = format!(
                        "OwnerOf field '{}' is {:?}, expected Pubkey",
                        field_path, field_ref.field_type
                    );
                    return quote! { compile_error!(#err_msg); };
                }

                let fn_name_lit = fn_name_str;
                let owner_var = format_ident!("__sb_owner_of_{}", account_name);

                // Generate inline code to read the authority pubkey from account data.
                // We can't use named account bindings (they don't exist in wrapper scope),
                // so we find the account by iterating and reading the byte offset directly.
                let offset = match &field_ref.strategy {
                    snapshot::SnapshotStrategy::FixedOffset(off) => *off,
                    snapshot::SnapshotStrategy::BorshDeserPrefix(_) => {
                        let err_msg = format!(
                            "OwnerOf field '{}' uses Borsh prefix strategy which requires named account binding. \
                             Use a fixed offset for the authority field instead.",
                            field_path
                        );
                        return quote! { compile_error!(#err_msg); };
                    }
                };

                // Find the account by looking for one owned by this program with the right discriminator
                let disc_check = if let Some(disc) = accts.get(account_name).and_then(|a| a.discriminator.as_ref()) {
                    let disc_bytes = disc.clone();
                    let disc_len = disc_bytes.len();
                    quote! {
                        // Verify discriminator matches
                        let __disc_slice = &__acct_data[..#disc_len];
                        if __disc_slice != &[#(#disc_bytes),*] {
                            continue;
                        }
                    }
                } else {
                    quote! {} // No discriminator check — trust Anchor downstream
                };

                quote! {
                    // ── OwnerOf authority check: read authority from account data, find matching signer ──
                    let #owner_var: anchor_lang::prelude::Pubkey = {
                        // Find the target account in the accounts list by owner + discriminator
                        let mut __found_authority: Option<anchor_lang::prelude::Pubkey> = None;
                        for __acct in accounts.iter() {
                            if __acct.owner != program_id {
                                continue;
                            }
                            let __acct_data = __acct.try_borrow_data()
                                .map_err(|_| anchor_lang::solana_program::program_error::ProgramError::Custom(6073u32))?;
                            if __acct_data.len() < #offset + 32 {
                                continue;
                            }
                            #disc_check
                            // Read the 32-byte Pubkey at the configured offset
                            let mut __pk_buf = [0u8; 32];
                            __pk_buf.copy_from_slice(&__acct_data[#offset..#offset + 32]);
                            __found_authority = Some(anchor_lang::prelude::Pubkey::new_from_array(__pk_buf));
                            break;
                        }
                        match __found_authority {
                            Some(auth) => auth,
                            None => {
                                anchor_lang::prelude::msg!(
                                    "PERK_SANDBOX:type=unauthorized,ix={},reason=owner_account_not_found",
                                    #fn_name_lit
                                );
                                return Err(anchor_lang::solana_program::program_error::ProgramError::Custom(6010u32));
                            }
                        }
                    };

                    // Find a signer in the accounts list that matches the stored authority
                    let __owner_of_signer_found = accounts.iter().any(|__acct| {
                        __acct.is_signer && __acct.key == &#owner_var
                    });
                    if !__owner_of_signer_found {
                        anchor_lang::prelude::msg!(
                            "PERK_SANDBOX:type=unauthorized,ix={},reason=signer_not_owner",
                            #fn_name_lit
                        );
                        return Err(anchor_lang::solana_program::program_error::ProgramError::Custom(6010u32));
                    }
                }
            }
            Err(e) => {
                let err_msg = format!(
                    "OwnerOf authority check for '{}' failed: {}. \
                     Declare the account and authority field in sandbox.toml [accounts.{}.fields]",
                    path, e, account_name
                );
                return quote! { compile_error!(#err_msg); };
            }
        }
    } else {
        let err_msg = format!(
            "OwnerOf authority check for '{}' requires [accounts] section in sandbox.toml",
            path
        );
        quote! { compile_error!(#err_msg); }
    }
}

/// Convert an instruction_attr::InvariantType (4-variant parse representation)
/// into the canonical types::InvariantType (18-variant) for codegen.
fn resolve_invariant_type(inv: &instruction_attr::InvariantType) -> Option<types::InvariantType> {
    match inv {
        instruction_attr::InvariantType::Typed { kind, params } => {
            match kind.as_str() {
                "gte" => Some(types::InvariantType::Gte {
                    lhs: params.get("lhs")?.clone(),
                    rhs: params.get("rhs")?.clone(),
                }),
                "lte" => Some(types::InvariantType::Lte {
                    lhs: params.get("lhs")?.clone(),
                    rhs: params.get("rhs")?.clone(),
                }),
                "eq" => Some(types::InvariantType::Eq {
                    lhs: params.get("lhs")?.clone(),
                    rhs: params.get("rhs")?.clone(),
                }),
                "immutable" => Some(types::InvariantType::Immutable {
                    field: params.get("field")?.clone(),
                }),
                "non_negative" => Some(types::InvariantType::NonNegative {
                    field: params.get("field")?.clone(),
                }),
                "max_decrease" => Some(types::InvariantType::MaxDecrease {
                    field: params.get("field")?.clone(),
                    pct: params.get("pct")?.parse().ok()?,
                }),
                "max_increase" => Some(types::InvariantType::MaxIncrease {
                    field: params.get("field")?.clone(),
                    pct: params.get("pct")?.parse().ok()?,
                    max_absolute: params.get("max_absolute").and_then(|v| v.parse().ok()),
                }),
                "delta_bound" => Some(types::InvariantType::DeltaBound {
                    field: params.get("field")?.clone(),
                    max: params.get("max")?.parse().ok()?,
                }),
                "conserve" => Some(types::InvariantType::Conserve {
                    field: params.get("field")?.clone(),
                }),
                "supply_conservation" => Some(types::InvariantType::SupplyConservation {
                    mint: params.get("mint")?.clone(),
                }),
                "lamport_conservation" => Some(types::InvariantType::LamportConservation),
                "payout_bounded" => Some(types::InvariantType::PayoutBounded {
                    outflow: params.get("outflow")?.clone(),
                    formula: params.get("formula")?.clone(),
                }),
                "aggregate_gte" => Some(types::InvariantType::AggregateGte {
                    field: params.get("field")?.clone(),
                    aggregate: params.get("aggregate")?.clone(),
                }),
                "account_guard" => Some(types::InvariantType::AccountGuard),
                "monotonic" => {
                    let field = params.get("field")?.clone();
                    let dir = match params.get("direction").map(|s| s.as_str()) {
                        Some("increasing") => types::MonotonicDirection::Increasing,
                        Some("decreasing") => types::MonotonicDirection::Decreasing,
                        _ => return None,
                    };
                    Some(types::InvariantType::Monotonic { field, direction: dir })
                }
                "when" => {
                    let condition = params.get("condition")?.clone();
                    let inner_kind = params.get("inner_kind")?.clone();
                    // Recursively resolve the inner invariant
                    let inner_params = params.clone();
                    let inner_inv = instruction_attr::InvariantType::Typed {
                        kind: inner_kind,
                        params: inner_params,
                    };
                    let inner = resolve_invariant_type(&inner_inv)?;
                    Some(types::InvariantType::When {
                        condition,
                        inner: Box::new(inner),
                    })
                }
                _ => None,
            }
        }
        instruction_attr::InvariantType::TxCumulativeDecrease { field, max_pct } => {
            Some(types::InvariantType::TxCumulativeDecrease {
                field: field.clone(),
                max_pct: *max_pct,
            })
        }
        instruction_attr::InvariantType::Custom { check_fn, cu_budget } => {
            Some(types::InvariantType::Custom {
                check_fn: check_fn.clone(),
                cu_budget: *cu_budget,
            })
        }
        instruction_attr::InvariantType::Named(name) => {
            Some(types::InvariantType::Named(name.clone()))
        }
    }
}

/// Collect field path strings from an instruction's invariants.
/// Extracts "account.field" paths from the instruction_attr::InvariantType variants.
fn collect_field_paths_from_instruction_meta(meta: &instruction_attr::InstructionMeta) -> Vec<String> {
    let mut paths = Vec::new();
    for inv in &meta.invariants {
        match inv {
            instruction_attr::InvariantType::TxCumulativeDecrease { field, .. } => {
                paths.push(field.clone());
            }
            instruction_attr::InvariantType::Typed { params, .. } => {
                // Extract field paths from key-value params
                if let Some(field) = params.get("field") {
                    paths.push(field.clone());
                }
                if let Some(lhs) = params.get("lhs") {
                    paths.push(lhs.clone());
                }
                if let Some(rhs) = params.get("rhs") {
                    // Only add rhs if it looks like a field path (contains a dot)
                    if rhs.contains('.') {
                        paths.push(rhs.clone());
                    }
                }
                if let Some(outflow) = params.get("outflow") {
                    paths.push(outflow.clone());
                }
                if let Some(mint) = params.get("mint") {
                    paths.push(mint.clone());
                }
            }
            instruction_attr::InvariantType::Named(_) => {
                // Named invariants: fields resolved when the invariant definition is known
                // (not available at this stage)
            }
            instruction_attr::InvariantType::Custom { .. } => {
                // Custom invariants use InvariantContext, not individual field snapshots
            }
        }
    }
    paths
}

/// Parse the `config = "sandbox.toml"` attribute argument.
fn parse_config_path(attr: TokenStream) -> Option<String> {
    let attr2: TokenStream2 = attr.into();
    let attr_str = attr2.to_string();
    if attr_str.contains("config") {
        let parts: Vec<&str> = attr_str.split('"').collect();
        if parts.len() >= 2 {
            return Some(parts[1].to_string());
        }
    }
    None
}

/// Convert parsed SandboxConfig (from config.rs) into program_attr::SandboxConfig.
fn build_program_config(config: &Option<config::SandboxConfig>) -> program_attr::SandboxConfig {
    let Some(config) = config else {
        return program_attr::SandboxConfig::default();
    };

    let reentrancy_mode = match &config.reentrancy {
        Some(r) => match r.mode {
            config::ReentrancyMode::Reject => program_attr::ReentrancyModeConfig::Reject,
            config::ReentrancyMode::Guard => program_attr::ReentrancyModeConfig::Guard,
            config::ReentrancyMode::Full => program_attr::ReentrancyModeConfig::Full,
        },
        None => program_attr::ReentrancyModeConfig::Guard,
    };

    let circuit_breakers = if let Some(cb) = &config.circuit_breakers {
        let categories: Vec<program_attr::CategoryMapping> = cb
            .categories
            .iter()
            .flat_map(|(cat_name, instructions)| {
                instructions.iter().map(move |ix| program_attr::CategoryMapping {
                    instruction: ix.clone(),
                    category: cat_name.clone(),
                })
            })
            .collect();

        let exempt_instructions = cb
            .tvl_cliff
            .as_ref()
            .and_then(|t| t.exempt.as_ref())
            .map(|e| e.instructions.clone())
            .unwrap_or_default();

        program_attr::CircuitBreakerConfig {
            enabled: cb.enabled,
            tvl_cliff_enabled: cb.tvl_cliff.is_some(),
            tvl_cliff_track_field: cb.tvl_cliff.as_ref().map(|t| t.track_field.clone()),
            tvl_cliff_field_offset: cb.tvl_cliff.as_ref().and_then(|t| {
                // Resolve field offset from accounts config
                let parts: Vec<&str> = t.track_field.splitn(2, '.').collect();
                if parts.len() == 2 {
                    config.accounts.as_ref()
                        .and_then(|accts| accts.get(parts[0]))
                        .and_then(|acct| acct.fields.get(parts[1]))
                        .and_then(|field| field.offset)
                } else {
                    None
                }
            }),
            tvl_cliff_field_size: 8, // u64
            tvl_cliff_window_slots: cb.tvl_cliff.as_ref().map(|t| t.window_slots).unwrap_or(0),
            tvl_cliff_window_seconds: cb.tvl_cliff.as_ref()
                .and_then(|t| t.window_seconds)
                .map(|s| s as i64)
                .unwrap_or(0),
            tvl_cliff_action: cb.tvl_cliff.as_ref()
                .map(|t| match &t.action {
                    config::BreakerAction::RejectCurrent => "reject_current",
                    config::BreakerAction::Pause => "pause",
                    config::BreakerAction::CloseOnly => "close_only",
                    config::BreakerAction::PauseLiquidations => "pause_liquidations",
                })
                .unwrap_or("reject_current")
                .to_string(),
            tvl_cliff_budgets: cb.tvl_cliff.as_ref()
                .map(|t| t.budgets.iter()
                    .map(|(cat, b)| (cat.clone(), b.max_decrease_pct))
                    .collect())
                .unwrap_or_default(),
            event_counters: Vec::new(),
            per_tx_threshold_enabled: false,
            per_tx_max_decrease_bps: 0,
            categories,
            exempt_instructions,
            scope: match cb.scope {
                config::CircuitBreakerScope::Global => "global".to_string(),
                config::CircuitBreakerScope::PerMarket => "per_market".to_string(),
            },
        }
    } else {
        program_attr::CircuitBreakerConfig::default()
    };

    // Extract keys config
    let keys = config
        .keys
        .as_ref()
        .cloned()
        .unwrap_or_default();

    // Extract recovery & close-only instructions from recovery config
    let mut mode = program_attr::ModeConfig::default();
    if let Some(recovery) = &config.recovery {
        if let Some(bypass) = &recovery.emergency_bypass {
            if bypass.enabled {
                // Recovery instructions are those marked with #[sandbox_recovery]
                // Close-only instructions are configured in categories
                // For now, populate from circuit breaker categories if available
            }
        }
    }
    // Close-only instructions: withdrawal + liquidation categories
    if let Some(cb) = &config.circuit_breakers {
        for (cat_name, instructions) in &cb.categories {
            match cat_name.as_str() {
                "withdrawal" | "liquidation" => {
                    mode.close_only_instructions.extend(instructions.clone());
                }
                _ => {}
            }
        }
    }

    // Extract rate limit config
    let rate_limits = config.rate_limits.as_ref().map(|rl| {
        program_attr::RateLimitConfig {
            global: rl.global.as_ref().map(|g| program_attr::RateLimitEntry {
                window_slots: g.window_slots,
                max_count: g.max_count,
            }),
            per_signer: rl.per_signer.as_ref().map(|s| program_attr::RateLimitEntry {
                window_slots: s.window_slots,
                max_count: s.max_count,
            }),
        }
    });

    program_attr::SandboxConfig {
        reentrancy_mode,
        circuit_breakers,
        mode,
        tx_anchor_enabled: false,
        pda_scope: String::new(),
        keys,
        rate_limits,
        oracle: config.oracle.as_ref().map(|o| program_attr::OraclePreCheckConfig {
            price_offset: o.price_offset,
            slot_offset: o.slot_offset,
            timestamp_offset: o.timestamp_offset,
            max_staleness_slots: o.max_staleness_slots,
            max_deviation_bps: o.max_deviation_bps,
            expected_owner: o.expected_owner.clone(),
        }),
    }
}

// ═══════════════════════════════════════════════════════════════════════════
// Other attribute macros - delegate to real parsers
// ═══════════════════════════════════════════════════════════════════════════

/// Instruction-level attribute. Implicit when #[invariant], #[authority], or #[bound] is present.
#[proc_macro_attribute]
pub fn sandbox_instruction(attr: TokenStream, item: TokenStream) -> TokenStream {
    let _ = attr;
    item
}

/// Declares a post-condition invariant on an instruction.
/// Parsed at compile time by instruction_attr::parse_instruction_attrs.
#[proc_macro_attribute]
pub fn invariant(attr: TokenStream, item: TokenStream) -> TokenStream {
    // Attributes are parsed by parse_instruction_attrs when processing the module.
    // The attribute itself is passed through so syn can see it on the ItemFn.
    let _ = attr;
    item
}

/// Declares an authority requirement on an instruction.
/// Parsed at compile time by authority_attr::parse_authority_attr.
#[proc_macro_attribute]
pub fn authority(attr: TokenStream, item: TokenStream) -> TokenStream {
    let _ = attr;
    item
}

/// Declares input bounds on an instruction.
/// Parsed at compile time by bound_attr::parse_bound_attr.
#[proc_macro_attribute]
pub fn bound(attr: TokenStream, item: TokenStream) -> TokenStream {
    let _ = attr;
    item
}

/// Declares which circuit breaker category an instruction belongs to.
#[proc_macro_attribute]
pub fn circuit_breaker_category(attr: TokenStream, item: TokenStream) -> TokenStream {
    let _ = attr;
    item
}
